[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
base_sepolia="${BASE_SEPOLIA_RPC_URL}"

[etherscan]
base_sepolia = { key = "${SEPOLIA_SCAN_KEY}",chain = 84532,url = "https://api-sepolia.basescan.org/api"}
